language: python

python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "pypy"

# Use container-based infrastructure
sudo: false

install:
 # Coveralls 4.0 doesn't support Python 3.2
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then pip install coverage==3.7.1; fi
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then pip install coverage; fi

script: nosetests --with-coverage --cover-package=twitter

after_success:
  - coveralls
  - pip install pep8 pyflakes
  - pep8 twitter/*.py
  - pyflakes twitter/*.py
  - pep8 tests/*.py
  - pyflakes tests/*.py

matrix:
  allow_failures:
    - python: "pypy"
